### ISSUE TITLE
Aplozic Android SDK 5.8.2 | java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Lalitkhandelwal** [AppLozic/Applozic-Android-SDK#323]
I'm using 5.8.2 version with firebase & gms 15.0.0 but its working fine with 11.8.0

 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
        at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source)
        at com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity.onCreate(ConversationActivity.java:411)
        at android.app.Activity.performCreate(Activity.java:6864)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6205)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf" on path: ""
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source) 
        at com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity.onCreate(ConversationActivity.java:411) 
        at android.app.Activity.performCreate(Activity.java:6864) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6205) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by Sunilkumarr** [comment]
@Lalitkhandelwal Looks like new version of google play service   is causing an miss match version we will update the same in our coming release, You can try using  11.8.0

**Comment by Sunilkumarr** [comment]
You can use it added support for google  play service 15.0.0                                                                    
 ```compile 'com.applozic.communication.uiwidget:mobicomkitui:5.8.4'```

**Comment by Lalitkhandelwal** [comment]
Thanks.
